name: "Terraform-Apply"

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/**'
      - '.github/workflows/*.yml'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Which environment to update.'
        type: choice
        default: 'dev'
        required: true 
        options:
        - dev
        - uat
        - prod

env:
 ENVIRONMENT:  github.event.inputs.environment || 'dev'

defaults:
  run:
    shell: bash
    working-directory: src/main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: "terraform-apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        env:
          AWS_REGION: eu-south-1
          IAM_ROLE: <iam role output after apply init>
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Read terraform version 
        id: read-version
        run: |
          echo "TERRAFORM_VERSION=`cat ../.terraform-version`" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        id: init
        run: |
          ./terraform.sh init ${{ env.ENVIRONMENT }}

      - name: Terraform Apply
        id: apply
        run: |
          ./terraform.sh apply ${{ env.ENVIRONMENT }} -auto-approve