name: "Terraform-Apply"

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/**'
      - '.github/workflows/*.yml'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Which environment to update.'
        type: choice
        required: true
        default: dev
        options:
        - dev
        - uat


jobs:
  manual-trigger:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: "terraform-apply (manual)"
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        env:
          AWS_REGION: eu-south-1
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply
        uses: ./.github/workflows/apply
        with:
          env: ${{ inputs.environment }}
          working-directory: src/main

  merge-trigger:
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      name: "terraform-apply (merge)"
      strategy:
        max-parallel: 1
        matrix:
          environment: [dev, uat, prod_w]
      runs-on: ubuntu-latest
      continue-on-error: false
      environment: ${{ matrix.environment }}
      permissions:
        id-token: write   # This is required for requesting the JWT
        contents: read    # This is required for actions/checkout

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure AWS Credentials
          env:
            AWS_REGION: eu-south-1
          uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
          with:
            role-to-assume: ${{ secrets.IAM_ROLE }}
            aws-region: ${{ env.AWS_REGION }}
        
        - name: Apply
          uses: ./.github/workflows/apply
          with:
            env: ${{ matrix.environment }}
            working-directory: src/main
